name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cython
        pip install buildozer
        pip install python-for-android

    - name: Install Android SDK Command-line Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip openjdk-11-jdk
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
        sudo mkdir -p /usr/local/android-sdk/cmdline-tools
        sudo unzip cmdline-tools.zip -d /usr/local/android-sdk/cmdline-tools
        sudo mv /usr/local/android-sdk/cmdline-tools/cmdline-tools /usr/local/android-sdk/cmdline-tools/tools
        export ANDROID_SDK_ROOT=/usr/local/android-sdk
        export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/tools/bin
        sdkmanager --sdk_root=${ANDROID_SDK_ROOT} --licenses || true
        sdkmanager --sdk_root=${ANDROID_SDK_ROOT} "build-tools;35.0.0" "platform-tools" "platforms;android-30"

    - name: Compile to APK
      run: |
        sudo apt-get install -y libzbar0  # If needed for dependencies
        buildozer android debug
        mkdir -p lib && mv bin/*.apk lib/

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: APK
        path: lib/*.apk
